import React, { Component } from 'react'
import Editor from '../Editor/Editor'
import ResumePage from '../ResumePage/ResumePage'

class mainDashBoardPage extends Component {
    state={
        color:null,
        font:null,
        birth:true,
        nation:true,
        address:true,
        status:true,
        email:true,
        phone:true,
        skype:false,
        web:true,
        linkdin:true,
        github:true,
        medium:true,
        quara:true,
        shareurl:null
    }
    handleColor=(color)=>{
        this.setState({
            color:color
        })
    }
    handlefont=(e)=>{
        this.setState({
            ...this.state,
            font:e
        })
    }
    handleBirth=(e)=>{
        this.setState({
            ...this.state,
            nation:e
        })
    }
    handleNation=(e)=>{
        this.setState({
            ...this.state,
            birth:e
        })
    }
    handleAddress=(e)=>{
        this.setState({
            ...this.state,
            address:e
        })
    }
    handleStatus=(e)=>{
        this.setState({
            ...this.state,
            status:e
        })
    }
    handleEmail=(e)=>{
        this.setState({
            ...this.state,
            email:e
        })
    }
    handlePhone=(e)=>{
        this.setState({
            ...this.state,
            phone:e
        })
    }
    handleSkype=(e)=>{
        this.setState({
            ...this.state,
            skype:e
        })
    }
    handleWeb=(e)=>{
        this.setState({
            ...this.state,
            web:e
        })
    }
    handleLinkdin=(e)=>{
        this.setState({
            ...this.state,
            linkdin:e
        })
    }
    handleGithub=(e)=>{
        this.setState({
            ...this.state,
            github:e
        })
    }
    handleMedium=(e)=>{
        this.setState({
            ...this.state,
            medium:e
        })
    }
    handleQuara=(e)=>{
        this.setState({
            ...this.state,
            quara:e
        })
    }
    handleshareurl=(url)=>{
        this.setState({
            ...this.state,
            shareurl:url
        })
    }
    
    render() {
        console.log(this.state.birth)
        return (
            <div>
                <Editor
                 handleColor={this.handleColor}
                 handlefont={this.handlefont}
                 handleBirth={this.handleBirth} 
                 handleNation={this.handleNation}
                 handleAddress={this.handleAddress}
                 handleStatus={this.handleStatus}
                 handleEmail={this.handleEmail}
                 handlePhone={this.handlePhone}
                 handleSkype={this.handleSkype}
                 handleWeb={this.handleWeb}
                 handleLinkdin={this.handleLinkdin}
                 handleGithub={this.handleGithub}
                 handleMedium={this.handleMedium}
                 handleQuara={this.handleQuara}
                 handleshareurl={this.handleshareurl}
                 shareurl={this.state.shareurl}
                 
                  />
                <ResumePage
                color={this.state.color}
                font={this.state.font}
                birth={this.state.birth}
                nation={this.state.nation}
                address={this.state.address}
                status={this.state.status}
                email={this.state.email}
                phone={this.state.phone}
                web={this.state.web}
                skype={this.state.skype}
                linkdin={this.state.linkdin}
                github={this.state.github}
                medium={this.state.medium}
                quara={this.state.quara}
                
                 />
                
            </div>
        )
    }
}
export default mainDashBoardPage